
files:
  include: 'src/app/**/*.scss'
  include: 'src/styles.scss'
# options:
#   formatter: scss
#   merge-default-rules: false
rules:
  EmptyLineBetweenBlocks:
    enabled: false
    ignore_single_line_blocks: true